#![allow(missing_docs)]

use crate::api::{DiagnosticCode, DiagnosticSeverity};

pub const DIAGNOSTIC_CODES: &[DiagnosticCode] = &[
    DiagnosticCode {
        code: "GNSS_NUMERIC_ACQ_INVALID",
        severity: DiagnosticSeverity::Error,
        meaning: "Acquisition results contain NaN/Inf",
        mitigation: "Inspect input IQ scaling and acquisition parameters.",
    },
    DiagnosticCode {
        code: "GNSS_NUMERIC_TRACK_INVALID",
        severity: DiagnosticSeverity::Error,
        meaning: "Tracking epoch contains NaN/Inf",
        mitigation: "Inspect loop configuration and correlator outputs.",
    },
    DiagnosticCode {
        code: "TRACK_NUMERIC_INVALID",
        severity: DiagnosticSeverity::Error,
        meaning: "Tracking epoch contains NaN/Inf",
        mitigation: "Inspect loop configuration and correlator outputs.",
    },
    DiagnosticCode {
        code: "GNSS_NUMERIC_OBS_INVALID",
        severity: DiagnosticSeverity::Error,
        meaning: "Observation contains NaN/Inf",
        mitigation: "Check tracking outputs and observables conversion.",
    },
    DiagnosticCode {
        code: "GNSS_OBS_NUMERIC_INVALID",
        severity: DiagnosticSeverity::Error,
        meaning: "Observation contains NaN/Inf",
        mitigation: "Check tracking outputs and observables conversion.",
    },
    DiagnosticCode {
        code: "GNSS_NUMERIC_PVT_INVALID",
        severity: DiagnosticSeverity::Error,
        meaning: "Navigation solution contains NaN/Inf",
        mitigation: "Inspect measurement inputs and solver configuration.",
    },
    DiagnosticCode {
        code: "GNSS_NUMERIC_T_RX_INVALID",
        severity: DiagnosticSeverity::Error,
        meaning: "Receiver time tag is not finite",
        mitigation: "Check sample clock and epoch timing logic.",
    },
    DiagnosticCode {
        code: "GNSS_EPOCH_ALIGN_FAIL",
        severity: DiagnosticSeverity::Warning,
        meaning: "Base/rover epoch alignment failed or had gaps",
        mitigation: "Check dataset timing and alignment tolerance.",
    },
    DiagnosticCode {
        code: "GNSS_OBS_VALIDATE_FAILED",
        severity: DiagnosticSeverity::Error,
        meaning: "Observation epoch validation failed",
        mitigation: "Inspect observation ordering, IDs, and time tags.",
    },
    DiagnosticCode {
        code: "GNSS_OBS_TIME_NON_MONOTONIC",
        severity: DiagnosticSeverity::Error,
        meaning: "Observation time tags are not monotonic",
        mitigation: "Ensure obs epochs are ordered by t_rx_s.",
    },
    DiagnosticCode {
        code: "GNSS_OBS_ID_INVALID",
        severity: DiagnosticSeverity::Error,
        meaning: "Observation contains invalid signal or satellite IDs",
        mitigation: "Check constellation, PRN, band, and code assignments.",
    },
    DiagnosticCode {
        code: "GNSS_OBS_CN0_INVALID",
        severity: DiagnosticSeverity::Error,
        meaning: "Observation CN0 outside expected bounds",
        mitigation: "Inspect CN0 estimation and scaling.",
    },
    DiagnosticCode {
        code: "GNSS_OBS_DOPPLER_INVALID",
        severity: DiagnosticSeverity::Error,
        meaning: "Observation Doppler outside expected bounds",
        mitigation: "Inspect Doppler sign conventions and units.",
    },
    DiagnosticCode {
        code: "GNSS_OBS_PSEUDORANGE_INVALID",
        severity: DiagnosticSeverity::Error,
        meaning: "Observation pseudorange outside expected bounds",
        mitigation: "Inspect code phase and receiver clock model.",
    },
    DiagnosticCode {
        code: "NAV_SOLUTION_RMS_INVALID",
        severity: DiagnosticSeverity::Error,
        meaning: "Nav solution RMS exceeds sanity threshold",
        mitigation: "Inspect measurement inputs and solver stability.",
    },
    DiagnosticCode {
        code: "NAV_POSITION_JUMP",
        severity: DiagnosticSeverity::Error,
        meaning: "Nav solution position jump exceeds threshold",
        mitigation: "Inspect time alignment and receiver clock.",
    },
    DiagnosticCode {
        code: "NAV_RAIM_SEPARATION",
        severity: DiagnosticSeverity::Warning,
        meaning: "Nav RAIM separation exceeded threshold",
        mitigation: "Inspect measurement consistency and RAIM settings.",
    },
    DiagnosticCode {
        code: "NAV_CLOCK_JUMP",
        severity: DiagnosticSeverity::Error,
        meaning: "Nav solution clock jump exceeds threshold",
        mitigation: "Inspect clock model and measurement quality.",
    },
    DiagnosticCode {
        code: "NAV_EPHEMERIS_GAP",
        severity: DiagnosticSeverity::Warning,
        meaning: "Ephemeris coverage gap detected",
        mitigation: "Provide a dataset with complete ephemeris coverage.",
    },
    DiagnosticCode {
        code: "NAV_INSUFFICIENT_SATS",
        severity: DiagnosticSeverity::Warning,
        meaning: "Nav solution attempted with insufficient satellites",
        mitigation: "Ensure at least 4 satellites with valid observations.",
    },
    DiagnosticCode {
        code: "NAV_SOLVER_FAILED",
        severity: DiagnosticSeverity::Warning,
        meaning: "Nav solver failed to converge or produce a solution",
        mitigation: "Inspect measurement inputs, weighting, and ephemeris coverage.",
    },
    DiagnosticCode {
        code: "TRACK_LOSS_OF_LOCK",
        severity: DiagnosticSeverity::Warning,
        meaning: "Tracking reported loss of lock",
        mitigation: "Inspect signal strength and tracking loop parameters.",
    },
    DiagnosticCode {
        code: "TRACK_BUDGET_EXCEEDED",
        severity: DiagnosticSeverity::Warning,
        meaning: "Tracking epoch exceeded configured time budget",
        mitigation: "Reduce channels or integration length, or increase budget.",
    },
    DiagnosticCode {
        code: "TRACK_ALLOCATIONS",
        severity: DiagnosticSeverity::Warning,
        meaning: "Allocations detected in tracking hot path",
        mitigation: "Enable alloc-trace and reduce per-epoch allocations.",
    },
    DiagnosticCode {
        code: "RTK_SD_NUMERIC_INVALID",
        severity: DiagnosticSeverity::Error,
        meaning: "RTK single-difference contains NaN/Inf",
        mitigation: "Inspect SD observation construction.",
    },
    DiagnosticCode {
        code: "RTK_SD_VARIANCE_INVALID",
        severity: DiagnosticSeverity::Error,
        meaning: "RTK single-difference variance is invalid",
        mitigation: "Inspect SD variance modeling.",
    },
    DiagnosticCode {
        code: "RTK_SD_CODE_INVALID",
        severity: DiagnosticSeverity::Error,
        meaning: "RTK single-difference code contains NaN/Inf",
        mitigation: "Inspect SD generation and input observables.",
    },
    DiagnosticCode {
        code: "RTK_SD_PHASE_INVALID",
        severity: DiagnosticSeverity::Error,
        meaning: "RTK single-difference phase contains NaN/Inf",
        mitigation: "Inspect SD phase formation and lock status.",
    },
    DiagnosticCode {
        code: "RTK_SD_DOPPLER_INVALID",
        severity: DiagnosticSeverity::Error,
        meaning: "RTK single-difference Doppler contains NaN/Inf",
        mitigation: "Inspect SD Doppler formation and tracking outputs.",
    },
    DiagnosticCode {
        code: "RTK_DD_CODE_INVALID",
        severity: DiagnosticSeverity::Error,
        meaning: "RTK double-difference code contains NaN/Inf",
        mitigation: "Inspect DD generation and reference selection.",
    },
    DiagnosticCode {
        code: "RTK_DD_PHASE_INVALID",
        severity: DiagnosticSeverity::Error,
        meaning: "RTK double-difference phase contains NaN/Inf",
        mitigation: "Inspect DD phase formation and ambiguity state.",
    },
    DiagnosticCode {
        code: "RTK_DD_DOPPLER_INVALID",
        severity: DiagnosticSeverity::Error,
        meaning: "RTK double-difference Doppler contains NaN/Inf",
        mitigation: "Inspect DD Doppler formation.",
    },
    DiagnosticCode {
        code: "RTK_DD_NUMERIC_INVALID",
        severity: DiagnosticSeverity::Error,
        meaning: "RTK double-difference contains NaN/Inf",
        mitigation: "Inspect DD observation construction.",
    },
    DiagnosticCode {
        code: "RTK_DD_VARIANCE_INVALID",
        severity: DiagnosticSeverity::Error,
        meaning: "RTK double-difference variance is invalid",
        mitigation: "Inspect DD variance modeling.",
    },
    DiagnosticCode {
        code: "RTK_BASELINE_INVALID",
        severity: DiagnosticSeverity::Error,
        meaning: "RTK baseline contains NaN/Inf",
        mitigation: "Inspect baseline solver and DD residuals.",
    },
    DiagnosticCode {
        code: "RTK_BASELINE_NUMERIC_INVALID",
        severity: DiagnosticSeverity::Error,
        meaning: "RTK baseline contains NaN/Inf",
        mitigation: "Inspect baseline solver and DD residuals.",
    },
    DiagnosticCode {
        code: "RTK_QUALITY_INVALID",
        severity: DiagnosticSeverity::Error,
        meaning: "RTK baseline quality metrics contain NaN/Inf",
        mitigation: "Inspect covariance propagation and residual metrics.",
    },
    DiagnosticCode {
        code: "RTK_QUALITY_NUMERIC_INVALID",
        severity: DiagnosticSeverity::Error,
        meaning: "RTK baseline quality metrics contain NaN/Inf",
        mitigation: "Inspect covariance propagation and residual metrics.",
    },
    DiagnosticCode {
        code: "RTK_PRECISION_INVALID",
        severity: DiagnosticSeverity::Error,
        meaning: "RTK precision metrics contain NaN/Inf",
        mitigation: "Inspect fix ratio and precision reporting.",
    },
    DiagnosticCode {
        code: "RTK_PRECISION_NUMERIC_INVALID",
        severity: DiagnosticSeverity::Error,
        meaning: "RTK precision metrics contain NaN/Inf",
        mitigation: "Inspect fix ratio and precision reporting.",
    },
    DiagnosticCode {
        code: "RTK_FIX_AUDIT_NUMERIC_INVALID",
        severity: DiagnosticSeverity::Error,
        meaning: "RTK fix audit contains NaN/Inf",
        mitigation: "Inspect fix audit calculations.",
    },
    DiagnosticCode {
        code: "PPP_EPOCH_INVALID",
        severity: DiagnosticSeverity::Error,
        meaning: "PPP solution epoch contains NaN/Inf",
        mitigation: "Inspect PPP filter outputs and residuals.",
    },
];
